apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0xxo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0xxo
    app.kubernetes.io/part-of: integ-app-jcnb
  name: hacbs-test-project-0xxo
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0xxo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0xxo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-nzje-tenant/integ-app-jcnb/hacbs-test-project-0xxo@sha256:4395cbcb7d7011756102da0baf73bb9cab5fc01a089a7be0fa0a005dbec1320a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
